language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=unstable
    - php: 7.2
    - php: 7.2
      env: setup=unstable
    - php: nightly
    - php: nightly
      env: setup=unstable
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'unstable' ]]; then travis_retry composer update --no-interaction --prefer-dist --no-suggest; fi

script: vendor/bin/phpunit --coverage-text
